### ISSUE TITLE
NoMethodError when trying to create post with tag_list field

### ISSUE THREAD

**Issue by NicWickman** [mbleigh/acts-as-taggable-on#899]
```
>> Resource.new("title"=>"Foobar", "url"=>"https://www.foobar.com", "content"=>"Test", "tag_list"=>"foo, bar")                                                                           
NoMethodError: undefined method `[]=' for nil:NilClass
        from (irb):3

```

Not sure what the issue is. Can anybody give me a hand? I am even able to add tags to resources that already exist, but I get this error when trying to create them with tags.

**Comment by BerndGoldschmidt** [comment]
Same here, even in the console (Rails 5.2.1):

````Ruby
irb(main):001:0> r = Rule.find(4)
  Rule Load (0.3ms)  SELECT  "rules".* FROM "rules" WHERE "rules"."id" = ? LIMIT ?  [["id", 4], ["LIMIT", 1]]
=> #<Rule id: 4, title: "rule title", description: "rule description", created_at: "2018-09-16 16:51:42", updated_at: "2018-09-16 19:01:57">
irb(main):002:0> r.tag_list = "test, second"
  ActsAsTaggableOn::Tagging Load (0.2ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_id" = ? AND "taggings"."taggable_type" = ?  [["taggable_id", 4], ["taggable_type", "Rule"]]
  ActsAsTaggableOn::Tag Load (0.2ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = ? AND "taggings"."taggable_type" = ? AND (taggings.context = 'tags' AND taggings.tagger_id IS NULL)  [["taggable_id", 4], ["taggable_type", "Rule"]]
Traceback (most recent call last):
        1: from (irb):2
NoMethodError (undefined method `[]=' for nil:NilClass)

````

**Comment by danielmyasnikov** [comment]
Oopsy, i've encountered the same issue

**Comment by danielmyasnikov** [comment]
Yes, so the issue is with Rails version `5.2.1`, where the issue is around `@changed_attributes` that do not exist: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/dirty.rb#L222

Upgrading to `6.0.1` version helps.

**Comment by skk2010** [comment]
This is a my patch to fix 

> NoMethodError (undefined method `[]=' for nil:NilClass)

only for gem version 5.0.0
not sure that it will work with Rails < 5.2

```
  module ActsAsTaggableOn::Taggable
    module Core
      def process_dirty_object(context, new_list)
        #return true
        value = new_list.is_a?(Array) ? ActsAsTaggableOn::TagList.new(new_list) : new_list
        attrib = "#{context.to_s.singularize}_list"

        if changed_attributes.include?(attrib)
          # The attribute already has an unsaved change.
          old = changed_attributes[attrib]
          attributes_changed_by_setter.delete(attrib) if old.to_s == value.to_s
        else
          old = tag_list_on(context)
          if self.class.preserve_tag_order
            attributes_changed_by_setter[attrib] = old if old.to_s != value.to_s
          else
            attributes_changed_by_setter[attrib] = old.to_s if old.sort != ActsAsTaggableOn.default_parser.new(value).parse.sort
          end
        end
      end
    end
  end
```

**Comment by psnider30** [comment]
@skk2010 Does this file need to be customized based on the attribute used for acts_as_taggable_on?
For example acts_as_taggable_on :industries

**Comment by skk2010** [comment]
> @skk2010 Does this file need to be customized based on the attribute used for acts_as_taggable_on?
> For example acts_as_taggable_on :industries

Not needed.
How it's done in our project:
1. We have some pathes and created in config/initializers a file which will load all of them.
This file contains few lines and one of them is:
`Dir[Rails.root.join('lib', 'monkey_patch', 'act_as_taggable_on_fix.rb').to_s].each { |path| require_dependency path }`
2. Next you need to create lib/monkey_patch/act_as_taggable_on_fix.rb with code published by me

That's it.

**Comment by seuros** [comment]
The stack this was reported on is long out of support, closing. If something similar shows up on Rails 8, please open a new issue.
