### ISSUE TITLE
undefined method `tag_list' after update from 3.2.3 to 3.4

### ISSUE THREAD

**Issue by TiSer** [mbleigh/acts-as-taggable-on#726]
I had an error when tried to use special characters from French as tags:

> incompatible character encodings: ASCII-8BIT and UTF-8

So, I tried to update gem to newer version from 3.2.3 to 3.4, as in FAQ. After bundle install I saw advice about migrations, so I done it:

> $ rake acts_as_taggable_on_engine:install:migrations
> => Rails 4.1.8 application starting in development 
> NOTE: Migration 1_acts_as_taggable_on_migration.rb from acts_as_taggable_on_engine has been skipped. Migration with the same name already exists.
> Copied migration 20160204134240_add_missing_taggable_index.acts_as_taggable_on_engine.rb from acts_as_taggable_on_engine

Then I restarted server and tried to run my app, but now I have error "_undefined method `tag_list'_".

What am I doing wrong?

**Comment by mupkoo** [comment]
I have the same problem updating to 3.3.6, 3.4.4 and 3.5.0.

**Comment by mupkoo** [comment]
Here is the stack trace

```
17:17:07 web.1    | Completed 500 Internal Server Error in 1257ms (ActiveRecord: 12.7ms)
17:17:07 web.1    |
17:17:07 web.1    | NoMethodError - undefined method `tags' for #<News:0x007fd7b2185fd8>:
17:17:07 web.1    |   activemodel (4.2.6) lib/active_model/attribute_methods.rb:433:in `method_missing'
17:17:07 web.1    |   app/views/app/news/show.html.slim:88:in `_app_views_app_news_show_html_slim__1022623830686451582_2190889120'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/template.rb:145:in `block in render'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/template.rb:333:in `instrument'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/template.rb:143:in `render'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
17:17:07 web.1    |   skylight (0.8.0) lib/skylight/probes/action_view.rb:22:in `block in render_with_layout'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
17:17:07 web.1    |   skylight (0.8.0) lib/skylight/probes/action_view.rb:21:in `render_with_layout'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:14:in `render'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/renderer.rb:46:in `render_template'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/renderer/renderer.rb:27:in `render'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/rendering.rb:100:in `_render_template'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/streaming.rb:217:in `_render_template'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/rendering.rb:83:in `render_to_body'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
17:17:07 web.1    |   actionpack (4.2.6) lib/abstract_controller/rendering.rb:25:in `render'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/rendering.rb:16:in `render'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
17:17:07 web.1    |   /Users/Mupko/.rbenv/versions/2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/core_ext/benchmark.rb:12:in `ms'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
17:17:07 web.1    |   activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:43:in `render'
17:17:07 web.1    |   responders (2.1.2) lib/action_controller/responder.rb:238:in `default_render'
17:17:07 web.1    |   responders (2.1.2) lib/action_controller/responder.rb:170:in `to_html'
17:17:07 web.1    |   responders (2.1.2) lib/responders/flash_responder.rb:107:in `to_html'
17:17:07 web.1    |   responders (2.1.2) lib/action_controller/responder.rb:163:in `respond'
17:17:07 web.1    |   responders (2.1.2) lib/action_controller/responder.rb:156:in `call'
17:17:07 web.1    |   responders (2.1.2) lib/action_controller/respond_with.rb:205:in `respond_with'
17:17:07 web.1    |   inherited_resources (1.6.0) lib/inherited_resources/actions.rb:13:in `show'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
17:17:07 web.1    |   actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
17:17:07 web.1    |   activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
17:17:07 web.1    |   actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
17:17:07 web.1    |   actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   omniauth (1.2.1) lib/omniauth/strategy.rb:186:in `call!'
17:17:07 web.1    |   omniauth (1.2.1) lib/omniauth/strategy.rb:164:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   omniauth (1.2.1) lib/omniauth/strategy.rb:186:in `call!'
17:17:07 web.1    |   omniauth (1.2.1) lib/omniauth/strategy.rb:164:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
17:17:07 web.1    |   warden (1.2.6) lib/warden/manager.rb:34:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/etag.rb:24:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/head.rb:13:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
17:17:07 web.1    |   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   activerecord (4.2.6) lib/active_record/query_cache.rb:36:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   activerecord (4.2.6) lib/active_record/migration.rb:377:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   better_errors (1.0.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
17:17:07 web.1    |   better_errors (1.0.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
17:17:07 web.1    |   better_errors (1.0.1) lib/better_errors/middleware.rb:56:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
17:17:07 web.1    |   web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
17:17:07 web.1    |   railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
17:17:07 web.1    |   railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
17:17:07 web.1    |   quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   actionpack (4.2.6) lib/action_dispatch/middleware/static.rb:120:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   railties (4.2.6) lib/rails/engine.rb:518:in `call'
17:17:07 web.1    |   railties (4.2.6) lib/rails/application.rb:165:in `call'
17:17:07 web.1    |   newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
17:17:07 web.1    |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
17:17:07 web.1    |   thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
17:17:07 web.1    |   thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
17:17:07 web.1    |   thin (1.6.4) lib/thin/connection.rb:53:in `process'
17:17:07 web.1    |   thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
17:17:07 web.1    |   eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
17:17:07 web.1    |   thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
17:17:07 web.1    |   thin (1.6.4) lib/thin/server.rb:162:in `start'
17:17:07 web.1    |   rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
17:17:07 web.1    |   rack (1.6.4) lib/rack/server.rb:286:in `start'
17:17:07 web.1    |   railties (4.2.6) lib/rails/commands/server.rb:80:in `start'
17:17:07 web.1    |   railties (4.2.6) lib/rails/commands/commands_tasks.rb:80:in `block in server'
17:17:07 web.1    |   railties (4.2.6) lib/rails/commands/commands_tasks.rb:75:in `server'
17:17:07 web.1    |   railties (4.2.6) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
17:17:07 web.1    |   railties (4.2.6) lib/rails/commands.rb:17:in `<top (required)>'
17:17:07 web.1    |   bin/rails:4:in `<main>'
```

**Comment by mupkoo** [comment]
Maybe its worth mentioning that `taggings` and `base_tags` are working. 

It looks like `ActsAsTaggableOn::Taggable::Core::ClassMethods#initialize_acts_as_taggable_on_core`  is never called

**Comment by mupkoo** [comment]
Completely my bad. I was monkey patching one of the modules. Sorry for the spam

**Comment by seuros** [comment]
This applies to Rails and Ruby versions the gem no longer supports. Current baseline is Rails 8 and Ruby 3.3, so closing.
