### ISSUE TITLE
undefined method `arity' for {:polymorphic=>true}:Hash

### ISSUE THREAD

**Issue by yshmarov** [mbleigh/acts-as-taggable-on#1056]
Rails 7alpha
Ruby 3

Getting this error when trying to add acts_as_taggable:
<img width="1084" alt="Screenshot 2021-10-26 at 14 10 18" src="https://user-images.githubusercontent.com/13472945/138875991-0da5583d-6b39-4a5b-b2bd-9b9b838e6fe1.png">

**Comment by shohey1226** [comment]
@yshmarov I've seen similar lines but when I upgraded to 8.x, the error is gone.

**Comment by francesco-loreti** [comment]
Set branch master into Gemfile for resolve this problem:
`gem 'acts-as-taggable-on', github: 'mbleigh/acts-as-taggable-on', branch: 'master'`

**Comment by seuros** [comment]
This applies to Rails and Ruby versions the gem no longer supports. Current baseline is Rails 8 and Ruby 3.3, so closing.
